# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: r
sudo: required
cache: packages
warnings_are_errors: false

before_install:
  
  - if [ "$TRAVIS_BRANCH" == "master" ]; then sudo add-apt-repository ppa:zarquon42/ppa -y; fi
  - if [ "$TRAVIS_BRANCH" != "master" ]; then sudo add-apt-repository ppa:zarquon42/statismo-develop -y; fi
  - sudo apt-get update -qq
  - sudo apt-get install --install-recommends -y statismo-dev cmake

repos:
  CRAN: https://cloud.r-project.org

r_binary_packages:
 - rgl
 - rvcg
 - morpho
 - testthat 

notifications:
  email:
    on_success: change
    on_failure: change

env:
  global:
    - R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
    - _R_CHECK_FORCE_SUGGESTS_: false
    - RGL_USE_NULL: true